// tests/browser-totp-safety.test.ts — BrowserWorker TOTP safety, detector, and scrubber tests.

import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { detectTotpPrompt } from "../src/vault/totp-detector";
import { BrowserWorker } from "../src/agent/browser-worker";
import { TaskSecretScrubber } from "../src/agent/secret-scrub";
import { encryptVaultPayload } from "../src/vault/service";
import type { Env } from "../src/env";

console.log("▶ Testing browser TOTP safety, detection boundaries & scrubber...");

{
  const res1 = detectTotpPrompt({
    elementText: "Two-Factor Authentication",
    nearbyText: "Please enter the code from your authenticator app",
    attributes: { name: "totp_code", autocomplete: "one-time-code", maxlength: 6 },
  });
  assert.equal(res1.isTotp, true);
  assert.ok(res1.matchedSignals?.includes("autocomplete_one_time_code"));

  const res2 = detectTotpPrompt({
    elementText: "Two-Step Verification",
    nearbyText: "Enter the 6-digit verification code generated by Google Authenticator",
    attributes: { id: "auth-code", maxlength: 6 },
  });
  assert.equal(res2.isTotp, true);
}

{
  const smsRes = detectTotpPrompt({
    elementText: "Two-Factor Authentication",
    nearbyText: "We sent a text message with a 6-digit verification code to your phone (SMS)",
    attributes: { autocomplete: "one-time-code", maxlength: 6 },
  });
  assert.equal(smsRes.isTotp, false);
  assert.equal(smsRes.rejectedReason, "not_totp_prompt");

  const emailRes = detectTotpPrompt({
    elementText: "Verify Your Identity",
    nearbyText: "Enter the email code sent to your email address",
    attributes: { name: "verification_code", maxlength: 6 },
  });
  assert.equal(emailRes.isTotp, false);
  assert.equal(emailRes.rejectedReason, "not_totp_prompt");

  const pushRes = detectTotpPrompt({
    elementText: "Two-Step Verification",
    nearbyText: "Approve on phone using push notification",
    attributes: { id: "code" },
  });
  assert.equal(pushRes.isTotp, false);

  const passkeyRes = detectTotpPrompt({
    elementText: "Sign in with Passkey",
    nearbyText: "Use your security key or biometric passkey",
    attributes: { name: "otp" },
  });
  assert.equal(passkeyRes.isTotp, false);

  const captchaRes = detectTotpPrompt({
    elementText: "Security Check",
    nearbyText: "Please solve the captcha verification",
    attributes: { name: "captcha_code" },
  });
  assert.equal(captchaRes.isTotp, false);

  // The HTML shape used by SMS/email OTP is not sufficient without authenticator-specific evidence.
  const genericOtp = detectTotpPrompt({
    elementText: "Verify your identity",
    nearbyText: "Enter the 6 digit code",
    attributes: { name: "verification_code", autocomplete: "one-time-code", maxlength: 6 },
  });
  assert.equal(genericOtp.isTotp, false);
  assert.equal(genericOtp.rejectedReason, "generic_otp_not_proven_totp");
}

{
  const split6 = detectTotpPrompt({
    elementText: "Enter Authenticator Code",
    nearbyText: "Enter the 6-digit code",
    inputCount: 6,
    attributes: { type: "text", maxlength: 1 },
  });
  assert.equal(split6.isTotp, true);
  assert.ok(split6.matchedSignals?.includes("split_input_count"));

  const split8 = detectTotpPrompt({
    elementText: "Authenticator verification",
    nearbyText: "Enter the 8-digit code from your authenticator app",
    inputCount: 8,
    attributes: { type: "number", maxlength: 1 },
  });
  assert.equal(split8.isTotp, true);
}

{
  const scrubber = new TaskSecretScrubber();
  const seed = "JBSWY3DPEHPK3PXP";
  const code = "654321";
  scrubber.register(seed);
  scrubber.register(code);
  const scrubbed = scrubber.scrub(`Successfully filled authenticator code ${code} using key ${seed}. Result: ok`);
  assert.equal(scrubbed.includes(code), false);
  assert.equal(scrubbed.includes(seed), false);
  assert.ok(scrubbed.includes("***"));
}

{
  const db = new DatabaseSync(":memory:");
  db.exec(`CREATE TABLE used_vault_items (task_id TEXT NOT NULL, candidate_id TEXT NOT NULL, PRIMARY KEY (task_id, candidate_id));`);
  const mockCtx: any = {
    storage: { sql: { exec: (s: string, ...args: unknown[]) => { const rows = db.prepare(s).all(...(args as never[])); return Object.assign(rows, { toArray: () => rows }); } } },
    id: { name: "ws-totp-test" },
    blockConcurrencyWhile: async (fn: any) => await fn(),
  };

  const ws = "ws-totp-test";
  const itemId = "vi_login_totp";
  const seed = "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ";
  const masterKey = "MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE=";
  const fields = {
    username: "alice",
    password: "password123",
    __totp: { status: "active", secretBase32: seed, algorithm: "SHA1", digits: 6, period: 30, issuer: "TestApp", createdAt: Date.now() },
  };
  const mockEnv: any = {
    BROWSER: {}, TOTP_ENABLED: "1", VAULT_MASTER_KEY: masterKey,
    DB: {
      prepare: (sql: string) => ({
        bind: (..._args: unknown[]) => ({
          first: async () => {
            if (sql.includes("FROM vault_items")) return { id: itemId, workspace_id: ws, kind: "login", label: "TestApp", account: "alice", origin: "https://example.com", has_totp: 1 };
            if (sql.includes("FROM encrypted_secrets")) return { ciphertext: await encryptVaultPayload({ VAULT_MASTER_KEY: masterKey } as Env, ws, itemId, JSON.stringify(fields)) };
            return null;
          },
          run: async () => ({ meta: { changes: 1 } }),
        }),
      }),
      batch: async () => [],
    },
  };

  const worker = new (BrowserWorker as any)(mockCtx, mockEnv);
  worker.onStart();
  const insertedTexts: string[] = [];
  const markedSelectors: string[] = [];
  const mockCDP: any = { send: async (cmd: string, params: any) => { if (cmd === "Input.insertText") insertedTexts.push(params.text); return {}; } };
  const mockPage: any = {
    url: () => "https://example.com/login/mfa",
    mouse: { click: async () => {} },
    evaluate: async () => ({
      elementText: "Two-Factor Authentication Please enter your code from authenticator app",
      nearbyText: "Please enter your code from authenticator app",
      inputs: [{ selector: 'input[data-totp-idx="0"]', x: 100, y: 200, name: "totp", id: "totp_input", type: "text", autocomplete: "one-time-code", ariaLabel: "Verification Code", placeholder: "123456", maxlength: 6, filled: false }],
    }),
  };
  worker.markSecret = async (_page: any, _frame: number, selector: string) => { markedSelectors.push(selector); };

  const toolRes = await worker.fillTotpFromVault({ workspaceId: ws, taskId: "t_1", goal: "login" }, mockPage, mockCDP, itemId);
  assert.equal(toolRes.content, "Authenticator code filled.");
  assert.equal(!toolRes.content.match(/\d{6}/), true);
  assert.equal(insertedTexts.length, 1);
  assert.match(insertedTexts[0], /^\d{6}$/);
  assert.equal(markedSelectors.length, 1);
  assert.equal(markedSelectors[0], 'input[data-totp-idx="0"]');
  const scrubbedTranscript = worker.scrubSecrets(`Inserted code ${insertedTexts[0]} now.`);
  assert.equal(scrubbedTranscript.includes(insertedTexts[0]), false);
  const usedItems = db.prepare(`SELECT candidate_id FROM used_vault_items WHERE task_id='t_1'`).all();
  assert.equal(usedItems.length, 1);
  assert.equal((usedItems[0] as any).candidate_id, itemId);
}

{
  const db = new DatabaseSync(":memory:");
  db.exec(`CREATE TABLE used_vault_items (task_id TEXT NOT NULL, candidate_id TEXT NOT NULL, PRIMARY KEY (task_id, candidate_id));`);
  const mockCtx: any = {
    storage: { sql: { exec: (s: string, ...args: unknown[]) => Object.assign(db.prepare(s).all(...(args as never[])), { toArray() { return this; } }) } },
    id: { name: "ws-boundary" },
    blockConcurrencyWhile: async (fn: any) => await fn(),
  };
  const ws = "ws-boundary";
  const itemId = "vi_boundary";
  const masterKey = "MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE=";
  const seed = "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ";
  const fields = { username: "a", password: "p", __totp: { status: "active", secretBase32: seed, algorithm: "SHA1", digits: 6, period: 30, createdAt: Date.now() } };
  const mockEnv: any = {
    BROWSER: {}, TOTP_ENABLED: "1", VAULT_MASTER_KEY: masterKey,
    DB: {
      prepare: (sql: string) => ({ bind: () => ({ first: async () => sql.includes("FROM vault_items") ? { id: itemId, workspace_id: ws, kind: "login", label: "L", account: "a", origin: "https://x.test", has_totp: 1 } : sql.includes("FROM encrypted_secrets") ? { ciphertext: await encryptVaultPayload({ VAULT_MASTER_KEY: masterKey } as Env, ws, itemId, JSON.stringify(fields)) } : null, run: async () => ({ meta: { changes: 1 } }) }) }),
      batch: async () => [],
    },
  };
  const worker = new (BrowserWorker as any)(mockCtx, mockEnv);
  worker.onStart();
  worker.markSecret = async () => {};
  const inserted: string[] = [];
  const slept: number[] = [];
  worker.sleep = async (ms: number) => { slept.push(ms); };
  let evalCount = 0;
  const page: any = {
    url: () => "https://x.test/login",
    mouse: { click: async () => {} },
    evaluate: async () => {
      evalCount++;
      if (evalCount === 1) return { elementText: "Authenticator verification code", nearbyText: "Enter verification code from your authenticator app", inputs: [{ selector: 'input[data-totp-idx="0"]', x: 1, y: 2, name: "otp", id: "otp", type: "text", autocomplete: "one-time-code", ariaLabel: "code", placeholder: "000000", maxlength: 6, filled: false }] };
      return "Invalid code. Please try again.";
    },
  };
  const cdp: any = { send: async (cmd: string, params: any) => { if (cmd === "Input.insertText") inserted.push(params.text); return {}; } };
  const res = await worker.fillTotpFromVault({ workspaceId: ws, taskId: "t_b", goal: "login" }, page, cdp, itemId);
  assert.equal(res.content, "Authenticator code filled.");
  assert.ok(inserted.length <= 2);
  assert.equal(res.content.includes(inserted[0]), false);
}

console.log("✔ Browser TOTP safety tests passed!");
